# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ActionOverlayDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

#  pod 'ModesoActionOverlay’, :git => 'https://github.com/Modeso/ModesoActionOverlay.git', :branch => 'Optimization'
pod 'ModesoActionOverlay’, :path => '/Users/modeso-5/ModesoProjects/ModesoActionOverlay'

end
